--------------------------------------------------------
--  ファイルを作成しました - 木曜日-8月-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMERMANAGER"."CUSTOMER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"ADDRESS1" VARCHAR2(100 BYTE), 
	"ADDRESS2" VARCHAR2(100 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"FAX" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."ID" IS 'ID';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."NAME" IS '氏名';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."ZIP" IS '郵便番号';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."ADDRESS1" IS '住所1';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."ADDRESS2" IS '住所2';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."TEL" IS '電話番号';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."FAX" IS 'FAX番号';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."CUSTOMER"."EMAIL" IS 'E-mailアドレス';
REM INSERTING into CUSTOMERMANAGER.CUSTOMER
SET DEFINE OFF;
Insert into CUSTOMERMANAGER.CUSTOMER (ID,NAME,ZIP,ADDRESS1,ADDRESS2,TEL,FAX,EMAIL) values (1,'鈴木一朗','111-1111','東京都千代田区千代田 1-X','千代田ビル1F','03-1111-XXXX','03-1111-XXXX','ichiro@example.com');
Insert into CUSTOMERMANAGER.CUSTOMER (ID,NAME,ZIP,ADDRESS1,ADDRESS2,TEL,FAX,EMAIL) values (2,'田宮二郎','222-2222','神奈川県神奈川市神奈川 1-X','神奈川ビル1F','045-222-XXXX','045-222-XXXX','jiro@example.com');
Insert into CUSTOMERMANAGER.CUSTOMER (ID,NAME,ZIP,ADDRESS1,ADDRESS2,TEL,FAX,EMAIL) values (3,'北島三郎','333-3333','埼玉県埼玉市埼玉 1-X','埼玉ビル1F','048-333-XXXX','048-333-XXXX','saburo@example.com');
Insert into CUSTOMERMANAGER.CUSTOMER (ID,NAME,ZIP,ADDRESS1,ADDRESS2,TEL,FAX,EMAIL) values (4,'伊東四朗','444-4444','千葉県千葉市千葉 1-X','千葉ビル1F','043-444-XXXX','043-444-XXXX','shiro@example.com');
--------------------------------------------------------
--  DDL for Index SYS_C007313
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMERMANAGER"."SYS_C007313" ON "CUSTOMERMANAGER"."CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMERMANAGER"."CUSTOMER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
