--------------------------------------------------------
--  ファイルを作成しました - 木曜日-8月-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOGIN_USER
--------------------------------------------------------

  CREATE TABLE "CUSTOMERMANAGER"."LOGIN_USER" 
   (	"ID" NUMBER(*,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"LVL" NUMBER(3,0), 
	"NAME" VARCHAR2(60 BYTE), 
	"PWD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CUSTOMERMANAGER"."LOGIN_USER"."ID" IS 'ID';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."LOGIN_USER"."LOGIN" IS 'ログイン名';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."LOGIN_USER"."LVL" IS '権限';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."LOGIN_USER"."NAME" IS 'ユーザー名';
   COMMENT ON COLUMN "CUSTOMERMANAGER"."LOGIN_USER"."PWD" IS 'ログインパスワード';
REM INSERTING into CUSTOMERMANAGER.LOGIN_USER
SET DEFINE OFF;
Insert into CUSTOMERMANAGER.LOGIN_USER (ID,LOGIN,LVL,NAME,PWD) values (1,'admin',2,'システム管理者','gclU2Vf6aETm4uAuaRsw8g==');
Insert into CUSTOMERMANAGER.LOGIN_USER (ID,LOGIN,LVL,NAME,PWD) values (2,'ichiro',1,'日本一郎','RMWS4TvVM46gWXvI+ESiig==');
Insert into CUSTOMERMANAGER.LOGIN_USER (ID,LOGIN,LVL,NAME,PWD) values (3,'jiro',0,'東京二郎','9kDKfaIle0keqYyXiTMx4A==');
--------------------------------------------------------
--  DDL for Index SYS_C007311
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMERMANAGER"."SYS_C007311" ON "CUSTOMERMANAGER"."LOGIN_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007312
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMERMANAGER"."SYS_C007312" ON "CUSTOMERMANAGER"."LOGIN_USER" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LOGIN_USER
--------------------------------------------------------

  ALTER TABLE "CUSTOMERMANAGER"."LOGIN_USER" ADD UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CUSTOMERMANAGER"."LOGIN_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
